AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Wasoko Tech Talk - Feb 12th 2021
Globals:
  Function:
    Timeout: 20
Resources:
  CiFileApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.wasoko.tech.api.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: s3://wasoko-tech-talk/f00219cbbeb9906e33c4615d11a89461
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        FilesController:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  CiFileApi:
    Description: Wasoko Tech Talk - Feb 12th 2021
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
    Export:
      Name: aws-wasoko-tech-talk-2-john
